import './globals.css'
import type { Metadata } from 'next'
import styles from './layout.module.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'playground',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <div className={styles.container}>
        <header className={styles.header}>
          <h1>블로그 제목</h1>
          <nav>
            <ul className={styles.navMenu}>
              <li><a href="#">홈</a></li>
              <li><a href="#">카테고리</a></li>
              <li><a href="#">태그</a></li>
              <li><a href="#">소개</a></li>
            </ul>
          </nav>
        </header>
        <div className={styles.content}>
          <div className={styles.sidebar}>
            {/* 사이드바 내용 추가 */}
          </div>
          <main className={styles.main}>
            {children}
          </main>
        </div>
        <footer className={styles.footer}>
          <p>© 2023 예시 블로그. All rights reserved.</p>
        </footer>
      </div>
    </html>
  )
}
